/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jbrew_jni_verifier_DoMath */

#ifndef _Included_org_jbrew_jni_verifier_DoMath
#define _Included_org_jbrew_jni_verifier_DoMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jbrew_jni_verifier_DoMath
 * Method:    addNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_jbrew_jni_verifier_DoMath_addNative
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
