language: java
install: true
after_success:
  - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
  - mvn verify sonar:sonar
  - mvn cobertura:cobertura

addons:
  sonarcloud:
    organization: "nealkumar"
    token: ${SONAR_TOKEN}

jdk:
  - openjdk8

script:
  - mvn clean verify sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
