language: java
install: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn verify sonar:sonar

addons:
  sonarcloud:
    organization: "nealkumar"
    token: ${env.SONAR_TOKEN}

jdk:
  - openjdk8

script:
  - mvn clean verify sonar:sonar -Pcoverage

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'