version: 0.2

phases:
  install:
    runtime-versions:
      - java: corretto11    
  pre_build:
    commands:
      - echo Build has commenced on `date`
  build:
    commands:
      - java -version
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/concurrent-0.0.1-SNAPSHOT.jar
