/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jbrew_jni_examples_SayHi */

#ifndef _Included_org_jbrew_jni_examples_SayHi
#define _Included_org_jbrew_jni_examples_SayHi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jbrew_jni_examples_SayHi
 * Method:    sayHi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jbrew_jni_examples_SayHi_sayHi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
