/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jbrew_cbrew_validator_Validator_PThreadValidator */

#ifndef _Included_org_jbrew_cbrew_validator_Validator_PThreadValidator
#define _Included_org_jbrew_cbrew_validator_Validator_PThreadValidator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jbrew_cbrew_validator_Validator_PThreadValidator
 * Method:    pthreadTest
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jbrew_cbrew_validator_Validator_00024PThreadValidator_pthreadTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
