/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jbrew_cbrew_validator_BasicMathValidatorCBrew */

#ifndef _Included_org_jbrew_cbrew_validator_BasicMathValidatorCBrew
#define _Included_org_jbrew_cbrew_validator_BasicMathValidatorCBrew
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jbrew_cbrew_validator_BasicMathValidatorCBrew
 * Method:    addNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_jbrew_cbrew_validator_BasicMathValidatorCBrew_addNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_jbrew_cbrew_validator_BasicMathValidatorCBrew
 * Method:    subNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_jbrew_cbrew_validator_BasicMathValidatorCBrew_subNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_jbrew_cbrew_validator_BasicMathValidatorCBrew
 * Method:    multNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_jbrew_cbrew_validator_BasicMathValidatorCBrew_multNative
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
