/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jbrew_cbrew_validator_Validator_MallocValidator */

#ifndef _Included_org_jbrew_cbrew_validator_Validator_MallocValidator
#define _Included_org_jbrew_cbrew_validator_Validator_MallocValidator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jbrew_cbrew_validator_Validator_MallocValidator
 * Method:    mallocTest
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jbrew_cbrew_validator_Validator_00024MallocValidator_mallocTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
