/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jbrew_cbrew_validator_SayHiCBrew */

#ifndef _Included_org_jbrew_cbrew_validator_SayHiCBrew
#define _Included_org_jbrew_cbrew_validator_SayHiCBrew
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jbrew_cbrew_validator_SayHiCBrew
 * Method:    sayHi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jbrew_cbrew_validator_SayHiCBrew_sayHi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
