/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jbrew_cbrew_espresso_SumOperation_NativeAdapter */

#ifndef _Included_org_jbrew_cbrew_espresso_SumOperation_NativeAdapter
#define _Included_org_jbrew_cbrew_espresso_SumOperation_NativeAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jbrew_cbrew_espresso_SumOperation_NativeAdapter
 * Method:    sumSequential
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_org_jbrew_cbrew_espresso_SumOperation_00024NativeAdapter_sumSequential
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     org_jbrew_cbrew_espresso_SumOperation_NativeAdapter
 * Method:    sumParallel
 * Signature: (I[II)I
 */
JNIEXPORT jint JNICALL Java_org_jbrew_cbrew_espresso_SumOperation_00024NativeAdapter_sumParallel
  (JNIEnv *, jobject, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
