/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jbrew_cbrew_espresso_SumOperation */

#ifndef _Included_org_jbrew_cbrew_espresso_SumOperation
#define _Included_org_jbrew_cbrew_espresso_SumOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jbrew_cbrew_espresso_SumOperation_DEFAULT_NUM_THREADS
#define org_jbrew_cbrew_espresso_SumOperation_DEFAULT_NUM_THREADS 5L
/*
 * Class:     org_jbrew_cbrew_espresso_SumOperation
 * Method:    sumSequential
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_org_jbrew_cbrew_espresso_SumOperation_sumSequential
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     org_jbrew_cbrew_espresso_SumOperation
 * Method:    sumParallel
 * Signature: (I[II)I
 */
JNIEXPORT jint JNICALL Java_org_jbrew_cbrew_espresso_SumOperation_sumParallel
  (JNIEnv *, jobject, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
