/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jbrew_jni_validator_BasicMathValidator */

#ifndef _Included_org_jbrew_jni_validator_BasicMathValidator
#define _Included_org_jbrew_jni_validator_BasicMathValidator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jbrew_jni_validator_BasicMathValidator
 * Method:    addNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_jbrew_jni_validator_BasicMathValidator_addNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_jbrew_jni_validator_BasicMathValidator
 * Method:    subNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_jbrew_jni_validator_BasicMathValidator_subNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_jbrew_jni_validator_BasicMathValidator
 * Method:    multNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_jbrew_jni_validator_BasicMathValidator_multNative
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
